### ISSUE TITLE
Feature: Support for reversed stack

### ISSUE THREAD

**Issue by erhant** [tanim0la/stack-pasta#1]
First of all this is an awesomely cute tool <3

I am a poor soul that writes stack comments in reverse, i.e.

```c
0x01    // [1]
0x02    // [1, 2] 
0x03    // [1, 2, 3] 
```

Could we have an extension setting that can decide the stack order? Perhaps a toggle option for "reversed stack".

**Comment by tanim0la** [comment]
absolutely!
this will be the next stack-pasta's feature ;)
